---
version: '3.9'
services:
  postgres:
    image: postgres:13-alpine
    restart: always
    volumes:
      - pgdata-flexibee:/var/lib/postgresql/data:rw
    env_file: config.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
  flexibee:
    restart: unless-stopped
    ports:
        - "5434:5434"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    env_file: config.env
volumes:
  pgdata-flexibee:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ynezz/data-postgres
